### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by anupamkakade** [geetotes/slactionmailer#4]
We have been using this gem in our project and its working perfect !!  Thanks . 
As of now we can send the message to only one channel which is configured in env file `SLACK_CHANNEL` . But it will be nice if we can select a channel while sending the slack mail. We have a requirement where we need to send a message to different channel depending on the type of operation.Is it possible to implement it ?

**Comment by geetotes** [comment]
Sure! I'll take a look this week

**Comment by geetotes** [comment]
Ok, support for multiple channels is in. Keep in mind that each channel has it's own incoming web hook url. You can now declare it in the mailer:
```
def notification
  mail(:from => 'from@example.com',           
       :to => 'to@example.com', 
       :subject => 'Subject',
       :channel => '#yourChanel'
       :webhook => 'https://your-webhook-url'
       :delivery_method => :slack)
end
```

The readme is updated as well. Enjoy :)

**Comment by anupamkakade** [comment]
Thanks a lot. Will test it and let you know.
